//
// Backend API for CAT ExamEase Platform: Superadmin Data Entry Endpoints
// - Add/edit users, results, schedules, hall tickets, notifications, revaluations
// - Integration with Supabase for all data operations
// - Secure endpoints require JWT authentication with "superadmin" role
//
const express = require("express");
const bodyParser = require("body-parser");
const { createClient } = require("@supabase/supabase-js");
const jwt = require("jsonwebtoken"); // Only for JWT role checks, JWT is generated by Supabase, validated here if needed
const cors = require("cors");

// Load Supabase credentials from .env or fallback to hardcoded values (for MVP/demo)
const SUPABASE_URL = process.env.SUPABASE_URL || "https://jzytsedlsvhnrfypwasm.supabase.co";
const SUPABASE_SERVICE_KEY = process.env.SUPABASE_SERVICE_KEY || process.env.SUPABASE_KEY ||
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6eXRzZWRsc3ZobnJmeXB3YXNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5MjEyMjAsImV4cCI6MjA2NzQ5NzIyMH0.Y_NeTtEhMP-mhFRFORnhQ_H3spyF6GQexR-k8-AWOn0";

const SUPABASE_JWT_SECRET = process.env.SUPABASE_JWT_SECRET || null;

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY);

const app = express();
const PORT = process.env.PORT || 4242;

app.use(cors());
app.use(bodyParser.json());

app.get("/", (req, res) => {
  res.json({ api: "CAT ExamEase Admin Backend", status: "OK" });
});

/**
 * PUBLIC_INTERFACE
 * Middleware to validate JWT in Authorization header and require "superadmin" role.
 */
async function requireSuperadmin(req, res, next) {
  // Supabase sets JWT in "Authorization: Bearer ..."
  const authHeader = req.headers.authorization || "";
  const token = authHeader.startsWith("Bearer ") ? authHeader.slice(7) : null;
  if (!token) return res.status(401).json({ error: "No token" });

  try {
    // Option 1: If SUPABASE_JWT_SECRET is available, locally validate
    if (SUPABASE_JWT_SECRET) {
      const payload = jwt.verify(token, SUPABASE_JWT_SECRET);
      // Superadmin check (supabase user_metadata or role == superadmin)
      if (
        (payload.role && payload.role === "superadmin") ||
        (payload.user_metadata && payload.user_metadata.role === "superadmin")
      ) {
        req.user = payload;
        return next();
      }
      return res.status(403).json({ error: "Admin privilege required" });
    } else {
      // Option 2: If JWT secret is not available, verify with Supabase API
      const { data, error } = await supabase.auth.getUser(token);
      if (error || !data || !data.user) return res.status(401).json({ error: "Invalid token" });
      const supaUser = data.user;
      if (
        (supaUser.role && supaUser.role === "superadmin") ||
        (supaUser.user_metadata && supaUser.user_metadata.role === "superadmin")
      ) {
        req.user = supaUser;
        return next();
      }
      return res.status(403).json({ error: "Admin privilege required" });
    }
  } catch (e) {
    return res.status(401).json({ error: "Token invalid/expired: " + e.message });
  }
}

/**
 * PUBLIC_INTERFACE
 * Add or update user (admin, candidate)
 * POST /admin/user - add user; PUT /admin/user/:id - update user
 */
app.post("/admin/user", requireSuperadmin, async (req, res) => {
  /**
   * Expected body: { email, password, name, role }
   * role in { "candidate", "admin", "superadmin" }
   */
  const { email, password, name, role } = req.body;
  if (!email || !password || !name || !role) return res.status(400).json({ error: "Missing fields" });
  // Use Supabase signUp API with "service_key"
  const { data, error } = await supabase.auth.admin.createUser({
    email,
    password,
    user_metadata: { name, role },
  });
  if (error) return res.status(400).json({ error: error.message });
  res.json({ user: data.user, id: data.user?.id });
});

app.put("/admin/user/:id", requireSuperadmin, async (req, res) => {
  const { id } = req.params;
  const fields = {};
  if (req.body.email) fields.email = req.body.email;
  if (req.body.password) fields.password = req.body.password;
  if (req.body.name || req.body.role)
    fields.user_metadata = {
      ...(req.body.name && { name: req.body.name }),
      ...(req.body.role && { role: req.body.role }),
    };
  if (Object.keys(fields).length === 0) return res.status(400).json({ error: "No update fields" });
  const { data, error } = await supabase.auth.admin.updateUserById(id, fields);
  if (error) return res.status(400).json({ error: error.message });
  res.json({ user: data.user });
});

/**
 * PUBLIC_INTERFACE
 * Add/edit result
 */
app.post("/admin/result", requireSuperadmin, async (req, res) => {
  // Body: user_id, exam_name, score, status (pass/fail), date
  const { user_id, exam_name, score, status, date } = req.body;
  if (!user_id || !exam_name || score === undefined)
    return res.status(400).json({ error: "Missing fields" });
  const { data, error } = await supabase.from("results").insert([{ user_id, exam_name, score, status, date }]);
  if (error) return res.status(400).json({ error: error.message });
  res.json({ inserted: data });
});

app.put("/admin/result/:id", requireSuperadmin, async (req, res) => {
  const { id } = req.params;
  const fields = req.body;
  if (Object.keys(fields).length === 0) return res.status(400).json({ error: "No update fields" });
  const { data, error } = await supabase.from("results").update(fields).eq("id", id);
  if (error) return res.status(400).json({ error: error.message });
  res.json({ updated: data });
});

/**
 * PUBLIC_INTERFACE
 * Add/edit schedule
 */
app.post("/admin/schedule", requireSuperadmin, async (req, res) => {
  // Body: exam_name, exam_date, duration, venue
  const { exam_name, exam_date, duration, venue } = req.body;
  if (!exam_name || !exam_date || !venue)
    return res.status(400).json({ error: "Missing fields" });
  const { data, error } = await supabase.from("schedule").insert([{ exam_name, exam_date, duration, venue }]);
  if (error) return res.status(400).json({ error: error.message });
  res.json({ inserted: data });
});

app.put("/admin/schedule/:id", requireSuperadmin, async (req, res) => {
  const { id } = req.params;
  const fields = req.body;
  if (Object.keys(fields).length === 0) return res.status(400).json({ error: "No update fields" });
  const { data, error } = await supabase.from("schedule").update(fields).eq("id", id);
  if (error) return res.status(400).json({ error: error.message });
  res.json({ updated: data });
});

/**
 * PUBLIC_INTERFACE
 * Add/edit hall ticket
 */
app.post("/admin/hallticket", requireSuperadmin, async (req, res) => {
  // Body: user_id, exam_name, exam_date, centre, ticket_number, status
  const { user_id, exam_name, exam_date, centre, ticket_number, status } = req.body;
  if (!user_id || !exam_name || !exam_date || !ticket_number)
    return res.status(400).json({ error: "Missing fields" });
  const { data, error } = await supabase.from("halltickets").insert([
    { user_id, exam_name, exam_date, centre, ticket_number, status },
  ]);
  if (error) return res.status(400).json({ error: error.message });
  res.json({ inserted: data });
});

app.put("/admin/hallticket/:id", requireSuperadmin, async (req, res) => {
  const { id } = req.params;
  const fields = req.body;
  if (Object.keys(fields).length === 0) return res.status(400).json({ error: "No update fields" });
  const { data, error } = await supabase.from("halltickets").update(fields).eq("id", id);
  if (error) return res.status(400).json({ error: error.message });
  res.json({ updated: data });
});

/**
 * PUBLIC_INTERFACE
 * Add/edit notification
 */
app.post("/admin/notification", requireSuperadmin, async (req, res) => {
  // Body: user_id, message, type, created_at
  const { user_id, message, type } = req.body;
  if (!user_id || !message)
    return res.status(400).json({ error: "Missing fields" });
  const { data, error } = await supabase.from("notifications").insert([{ user_id, message, type }]);
  if (error) return res.status(400).json({ error: error.message });
  res.json({ inserted: data });
});

app.put("/admin/notification/:id", requireSuperadmin, async (req, res) => {
  const { id } = req.params;
  const fields = req.body;
  if (Object.keys(fields).length === 0) return res.status(400).json({ error: "No update fields" });
  const { data, error } = await supabase.from("notifications").update(fields).eq("id", id);
  if (error) return res.status(400).json({ error: error.message });
  res.json({ updated: data });
});

/**
 * PUBLIC_INTERFACE
 * Add/edit revaluation
 */
app.post("/admin/revaluation", requireSuperadmin, async (req, res) => {
  // Body: user_id, exam_name, reason, document_url, status
  const { user_id, exam_name, reason, document_url, status } = req.body;
  if (!user_id || !exam_name || !reason)
    return res.status(400).json({ error: "Missing fields" });
  const { data, error } = await supabase.from("revaluations").insert([
    { user_id, exam_name, reason, document_url, status },
  ]);
  if (error) return res.status(400).json({ error: error.message });
  res.json({ inserted: data });
});

app.put("/admin/revaluation/:id", requireSuperadmin, async (req, res) => {
  const { id } = req.params;
  const fields = req.body;
  if (Object.keys(fields).length === 0) return res.status(400).json({ error: "No update fields" });
  const { data, error } = await supabase.from("revaluations").update(fields).eq("id", id);
  if (error) return res.status(400).json({ error: error.message });
  res.json({ updated: data });
});

app.listen(PORT, () => {
  console.log(`Admin backend server listening on port ${PORT}`);
});
